#!/usr/bin/env python3
"""Generate polished Earth Online block and machine textures with Agnes.

Python/Pillow is only used for download, crop, downscale, and validation. The
visual source image is generated by Agnes.
"""

from __future__ import annotations

import argparse
import base64
import json
import pathlib
import re
import time
import urllib.parse

import requests
from PIL import Image


ROOT = pathlib.Path(__file__).resolve().parents[1]
ASSETS = ROOT / "neoforge-26.2" / "src" / "main" / "resources" / "assets" / "earth_online"
TMP = ROOT / "tmp" / "imagegen" / "agnes-block-textures"
PROVIDERS = pathlib.Path(r"C:\Users\du_ji\WorkBuddy\agnes\providers.json")

MODEL = "agnes-image-2.1-flash"
ENDPOINT = "https://apihub.agnes-ai.com/v1/images/generations"

BLOCKS = {
    "poor_magnetite_ore": ("poor magnetite ore in dark gray deepslate, sparse black metallic Fe3O4 crystals, subtle rusty brown iron oxide staining, realistic ore block"),
    "magnetite_ore": ("magnetite ore block, dark graphite-black metallic Fe3O4 crystals embedded in stone, strong readable mineral clusters, realistic geology texture"),
    "rich_magnetite_ore": ("rich magnetite ore block, dense black metallic Fe3O4 bands with reddish iron oxide highlights, high-grade iron ore lens texture"),
    "chalcopyrite_ore": ("chalcopyrite ore block, brass-gold CuFeS2 crystals with slight iridescent tarnish embedded in gray host rock, realistic copper sulfide ore"),
    "auriferous_quartz_vein": ("auriferous quartz vein block, milky white quartz with tiny native gold specks and gray host-rock cracks, realistic hydrothermal vein"),
    "bituminous_coal_seam": ("bituminous coal-bearing sedimentary rock block, glossy black coal bands embedded in dark shale, volatile-rich layered deposit, realistic geology texture"),
    "anthracite_coal_seam": ("anthracite coal-bearing sedimentary rock block, hard shiny high-carbon coal lenses in dense dark host rock, clean conchoidal highlights, realistic geology texture"),
    "kimberlite": ("kimberlite block, green-gray volcanic breccia with dark mantle fragments, realistic igneous pipe texture"),
    "diamondiferous_kimberlite": ("diamondiferous kimberlite block, green-gray kimberlite breccia with rare pale diamond glints, realistic ore-bearing pipe texture"),
    "lapis_lazuli_ore": ("lapis lazuli ore block, deep blue lazurite patches with white calcite and golden pyrite specks in host rock, realistic mineral texture"),
    "emerald_beryl_vein": ("emerald beryl vein block, green beryl crystals in pale quartz-feldspar pegmatite, realistic gem vein texture"),
    "redstone_mineral_ore": ("redstone mineral ore block, red cinnabar-like and hematite-like mineral grains in dark host rock, subtle glow-free realistic texture"),
    "cinnabar_vein": ("cinnabar vein block, vivid red HgS mineral vein in pale carbonate rock, realistic hydrothermal vein texture"),
    "jaw_crusher": ("modern jaw crusher module, matte graphite steel enclosure, two clean toothed jaws, hydraulic side cylinders, industrial sensor strips"),
    "ball_mill": ("modern ball mill module, enclosed rotating drum behind maintenance glass, brushed steel panels, precision bearing housings"),
    "sieve": ("modern vibrating sieve module, stainless mesh screen, compact vibration dampers, clean green-gray industrial housing"),
    "magnetic_separator": ("modern magnetic separator module, red-blue electromagnetic coil arcs, shielded steel casing, precise inspection window"),
    "flotation_cell": ("modern flotation cell module, teal chemical tank window, aeration bubbles, stainless pipe manifold"),
    "ore_roaster": ("modern ore roaster module, insulated refractory chamber, controlled orange heat glow, clean exhaust duct"),
    "reduction_furnace": ("modern reduction furnace module, sealed black steel shell, bright controlled molten core, ceramic insulation panels"),
    "leaching_tank": ("modern leaching tank module, acid-safe green vessel window, stainless flanges and dosing pipes"),
    "electrolytic_cell": ("modern electrolytic cell module, blue electrolyte window, copper electrodes, clean electrical bus bars"),
    "powder_press": ("modern powder press module, hydraulic ram, compacting die, powder tray, clean factory enclosure"),
    "chemical_reactor": ("modern chemical reactor module, pressure vessel face, digital gauge lights, bolted hatch, stainless pipe loop"),
    "distillation_column": ("modern distillation column module, sleek silver tray column, stacked sight glasses, blue instrumentation"),
    "mixer": ("modern industrial mixer module, enclosed impeller seen through round port, olive-gray steel body, small sensors"),
    "crystallizer": ("modern crystallizer module, bright blue crystal chamber, chilled stainless panels, clean condenser fittings"),
    "industrial_kiln": ("modern industrial kiln module, insulated rectangular firing chamber, controlled hot core, clean steel bands"),
    "gas_separator": ("modern gas separation skid module, pressure gauges, valve manifold, blue gas window, stainless fittings"),
    "fertilizer_granulator": ("modern fertilizer granulator module, enclosed granule drum, hopper port, green pellet stream behind glass"),
    "polymerizer": ("modern polymerizer module, sealed resin reactor, purple translucent vessel window, clean pipe manifold"),
    "steam_cracker": ("modern steam cracker train module, orange radiant coil window, black insulated casing, clean process tubes"),
    "synthesis_loop": ("modern high pressure synthesis loop module, green reactor ring, compact recycle pipes, safety instrumentation"),
    "absorption_tower": ("modern absorption tower module, packed column section, blue liquid spray window, clean vertical vents"),
    "industrial_machine_casing": ("modern modular industrial machine casing, satin steel composite panels, beveled seams, dark gray connector ribs"),
    "steel_process_pipe": ("modern steel process pipe block, clean thick pipe cross-section, flanged connector, blue-gray stainless metal"),
    "control_panel": ("modern industrial control panel, dark glass screen, clean indicator lights, flush buttons, brushed metal frame"),
    "industrial_machine_casing_assembled": ("formed large-machine outer shell block, seamless modern industrial casing, continuous panel lines, heavy steel structure"),
    "steel_process_pipe_assembled": ("formed large-machine process pipe block, connected stainless pipe corridor, flanges aligned to neighboring equipment, modern plant piping"),
    "control_panel_connected": ("connected large-machine control console block, illuminated modern operator panel, dark display glass, green status light, flush metal frame"),
}


def load_agnes_key() -> str:
    raw = PROVIDERS.read_text(encoding="utf-8", errors="ignore")
    try:
        data = json.loads(raw)
        keys = data["agnes"]["keys"]
        if isinstance(keys, list) and keys:
            return str(keys[0])
    except Exception:
        pass

    # Fallback for historically hand-edited provider files with a damaged later entry.
    agnes_pos = raw.find('"agnes"')
    if agnes_pos < 0:
        raise RuntimeError("Agnes provider not found in providers.json.")
    next_provider = raw.find('\n  "', agnes_pos + 8)
    agnes_raw = raw[agnes_pos: next_provider if next_provider > agnes_pos else len(raw)]
    keys_match = re.search(r'"keys"\s*:\s*\[(.*?)\]', agnes_raw, re.S)
    if not keys_match:
        raise RuntimeError("Agnes key list not found in providers.json.")
    keys = re.findall(r'"([^"]+)"', keys_match.group(1))
    if not keys:
        raise RuntimeError("Agnes provider has no usable keys.")
    return keys[0]


def prompt_for(block_id: str, descriptor: str) -> str:
    return (
        "Create one polished Minecraft mod block texture for Earth Online.\n"
        f"Block id: {block_id}\n"
        f"Subject: {descriptor}.\n"
        "Style: high-quality modern Minecraft mod block texture, 128x128 or higher source detail, orthographic square texture view, "
        "clean contemporary industrial or realistic geology art, not retro, not steampunk, not medieval, not rusty, not cartoonish, "
        "readable silhouette at small in-game scale, crisp pixel shapes, strong contrast, no text, "
        "no letters, no pseudo-letters, no numbers, no labels, no watermark, no UI, no inventory mockup.\n"
        "Composition: centered machine face or natural block surface, fills the square, clear iconic feature, "
        "subtle material detail, clean edges or mineral bands, soft ambient occlusion, no perspective scene, no background outside the texture.\n"
        "Output should be a single seamless-ish square texture suitable for a Minecraft block face."
    )


def request_image(key: str, block_id: str, descriptor: str, attempts: int = 5) -> bytes:
    body = {
        "model": MODEL,
        "prompt": prompt_for(block_id, descriptor),
        "size": "1024x1024",
        "n": 1,
    }
    last_error: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            response = requests.post(
                ENDPOINT,
                headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
                json=body,
                timeout=600,
            )
            response.raise_for_status()
            payload = response.json()
            break
        except requests.RequestException as exc:
            last_error = exc
            if attempt >= attempts:
                raise
            wait = min(120, 10 * attempt)
            print(f"  request failed for {block_id}, retry {attempt}/{attempts} after {wait}s: {exc}", flush=True)
            time.sleep(wait)
    else:
        raise RuntimeError(f"Agnes request failed for {block_id}: {last_error}")

    data = payload.get("data") or []
    if not data:
        raise RuntimeError(f"Agnes returned no image data for {block_id}: {payload}")
    image = data[0]
    if isinstance(image, dict) and image.get("b64_json"):
        return base64.b64decode(image["b64_json"])
    url = image.get("url") or image.get("image_url") if isinstance(image, dict) else None
    if not url:
        raise RuntimeError(f"Unsupported Agnes image payload for {block_id}: {payload}")
    if url.startswith("data:image"):
        return base64.b64decode(url.split(",", 1)[1])
    parsed = urllib.parse.urlparse(url)
    if not parsed.scheme:
        raise RuntimeError(f"Invalid image url for {block_id}: {url}")
    for attempt in range(1, attempts + 1):
        try:
            download = requests.get(url, timeout=600)
            download.raise_for_status()
            return download.content
        except requests.RequestException as exc:
            last_error = exc
            if attempt >= attempts:
                raise
            wait = min(120, 10 * attempt)
            print(f"  download failed for {block_id}, retry {attempt}/{attempts} after {wait}s: {exc}", flush=True)
            time.sleep(wait)
    raise RuntimeError(f"Agnes image download failed for {block_id}: {last_error}")


def downscale_block(source: pathlib.Path, target: pathlib.Path, size: int) -> None:
    img = Image.open(source).convert("RGBA")
    side = min(img.width, img.height)
    left = (img.width - side) // 2
    top = (img.height - side) // 2
    img = img.crop((left, top, left + side, top + side))
    # Downsample in stages to preserve recognizable shapes without mushy blur.
    for intermediate in (256, 128, 64, 32):
        if img.width > intermediate > size:
            img = img.resize((intermediate, intermediate), Image.Resampling.LANCZOS)
    img = img.resize((size, size), Image.Resampling.BICUBIC)
    target.parent.mkdir(parents=True, exist_ok=True)
    img.save(target)


def make_montage(block_ids: list[str], size: int) -> pathlib.Path:
    thumbs = []
    for block_id in block_ids:
        path = ASSETS / "textures" / "block" / f"{block_id}.png"
        if path.exists():
            thumbs.append((block_id, Image.open(path).convert("RGBA").resize((32, 32), Image.Resampling.NEAREST)))
    if not thumbs:
        raise RuntimeError("No generated textures found for montage.")
    cols = 6
    rows = (len(thumbs) + cols - 1) // cols
    montage = Image.new("RGBA", (cols * 40, rows * 40), (24, 24, 24, 255))
    for i, (_block_id, thumb) in enumerate(thumbs):
        x = (i % cols) * 40 + 4
        y = (i // cols) * 40 + 4
        montage.alpha_composite(thumb, (x, y))
    out = TMP / f"block_texture_montage_{size}px.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    montage.save(out)
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="regenerate textures even if final PNG exists")
    parser.add_argument("--only", nargs="*", default=[], help="specific block ids to generate")
    parser.add_argument("--limit", type=int, default=0, help="only generate first N selected textures")
    parser.add_argument("--size", type=int, default=128, choices=[16, 32, 64, 128, 256], help="final texture size")
    args = parser.parse_args()

    selected = args.only or list(BLOCKS)
    unknown = [block_id for block_id in selected if block_id not in BLOCKS]
    if unknown:
        raise SystemExit(f"Unknown block ids: {', '.join(unknown)}")

    key = load_agnes_key()
    TMP.mkdir(parents=True, exist_ok=True)
    generated = 0
    for block_id in selected:
        if args.limit and generated >= args.limit:
            break
        final = ASSETS / "textures" / "block" / f"{block_id}.png"
        raw = TMP / f"{block_id}.png"
        if final.exists() and not args.force:
            print(f"skip existing {block_id}")
            continue
        print(f"generating {block_id} with Agnes ...", flush=True)
        content = request_image(key, block_id, BLOCKS[block_id])
        raw.write_bytes(content)
        downscale_block(raw, final, args.size)
        generated += 1
        time.sleep(1.0)

    montage = make_montage(selected, args.size)
    print(f"Agnes block texture generation complete: generated={generated}, montage={montage}")


if __name__ == "__main__":
    main()
